### ISSUE TITLE
automate Box VM registration in scripts

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/examples#27]
Get the user's MAC address with this API:
```
GET https://test.camio.com/api/users/me/variables/box_vm_mac
```
If the user registers multiple Box VMs, then get additional MACs by appending a digit like:
```
GET https://test.camio.com/api/users/me/variables/box_vm_mac1
```

**Comment by jhallard** [comment]
can this be closed since we aren't really automating box registration? @jcmaslan
