### ISSUE TITLE
Add bookmarks.json in samples directory to show concrete example

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/examples#34]
Use the output from the "hello world" example to generate the bookmarks.json sample.

**Comment by jhallard** [comment]
okay do you have a default label white-list filter that I should use for this run? (to reduce spam)

**Comment by jcmaslan** [comment]
Yes, please include only "_ml_human", "fish", "tuna", "marlin", "yellowfin tuna", "bluefin tuna"

**Comment by jhallard** [comment]
Fixed in #36
